<script lang="ts">
  import { onMount } from "svelte";
  import DocumentTree from "./tree/DocumentTree.svelte";
  import Editor from "./editor/Editor.svelte";
  import { SAMPLE_BOOK } from "./fb2/sample";
  import type { FictionBook } from "./fb2/types";

  let fb: FictionBook | null = null;
  let filename = "(untitled)";
  let error = "";

  /** Call into the Wails-bound Go App if present; otherwise fall back to sample. */
  async function openFile() {
    error = "";
    try {
      // Wails runtime is injected at build time as window.go / window.runtime.
      // @ts-expect-error — bindings generated by `wails dev` / `wails build`.
      const runtime = window.runtime;
      // @ts-expect-error — generated bindings
      const App = window.go?.main?.App;
      if (!runtime || !App) {
        throw new Error("Wails bindings not available (running in plain vite dev?). Loaded bundled sample instead.");
      }
      const path: string = await runtime.OpenFileDialog({
        Title: "Open FB2 file",
        Filters: [{ DisplayName: "FictionBook (*.fb2;*.fb2.zip)", Pattern: "*.fb2;*.fb2.zip" }],
      });
      if (!path) return;
      fb = await App.OpenFile(path);
      filename = path.split(/[\\/]/).pop() ?? path;
    } catch (e) {
      error = (e as Error).message;
      fb = SAMPLE_BOOK;
      filename = "blank.fb2 (sample)";
    }
  }

  onMount(() => {
    document.title = "FictionBook Editor (Go)";
    // Auto-load sample so the editor surface is visible on first run.
    fb = SAMPLE_BOOK;
    filename = "blank.fb2 (sample)";
  });
</script>

<div class="layout">
  <header>
    <button on:click={openFile}>Open…</button>
    <span class="title">FictionBook Editor · <em>{filename}</em></span>
    {#if error}<span class="err">{error}</span>{/if}
  </header>

  <main>
    <aside><DocumentTree /></aside>
    <section><Editor {fb} /></section>
  </main>
</div>

<style>
  :global(body), :global(html) {
    margin: 0;
    height: 100%;
    background: #fafaf7;
    color: #222;
  }
  .layout {
    display: grid;
    grid-template-rows: 2.5rem 1fr;
    height: 100vh;
    font-family: -apple-system, "Segoe UI", sans-serif;
  }
  header {
    display: flex;
    align-items: center;
    padding: 0 0.75rem;
    gap: 0.75rem;
    background: #f1f1ec;
    border-bottom: 1px solid #d5d5cb;
  }
  header button {
    padding: 0.25rem 0.7rem;
    border: 1px solid #bbb;
    background: white;
    border-radius: 4px;
    cursor: pointer;
  }
  header button:hover { background: #fff8e5; }
  .title { font-size: 0.9rem; color: #444; }
  .err { color: #a33; font-size: 0.8rem; margin-left: auto; }
  main {
    display: grid;
    grid-template-columns: 260px 1fr;
    overflow: hidden;
  }
  aside {
    border-right: 1px solid #d5d5cb;
    overflow: auto;
    background: #f5f5f0;
    font-size: 0.9rem;
  }
  section {
    overflow: auto;
    background: white;
  }
</style>
